/// Production confidential-amount circuits verified on-chain via `sui::groth16`
/// (BN254 — the testnet/mainnet native). These prove the real settlement
/// primitive: a hidden `delta` moves from sender to recipient, balances stay
/// secret, and the proof enforces conservation + no-underflow.
///
/// Bytes generated by circuits/scripts/prove.sh from the production build
/// (Poseidon commitments, 64-bit range checks). The 4 public signals are the
/// commitments cSenderOld / cSenderNew / cRecipientOld / cRecipientNew.
#[test_only]
#[allow(implicit_const_copy)]
module groth16_poc::confidential_tests;

use sui::groth16::{Self, bn254};

fun verify(vk: vector<u8>, inputs: vector<u8>, proof: vector<u8>): bool {
    let curve = bn254();
    let pvk = groth16::prepare_verifying_key(&curve, &vk);
    let public_inputs = groth16::public_proof_inputs_from_bytes(inputs);
    let proof_points = groth16::proof_points_from_bytes(proof);
    groth16::verify_groth16_proof(&curve, &pvk, &public_inputs, &proof_points)
}

// transfer.circom: stream $500→$375, freelancer $0→$125, hidden delta=$125.
const TRANSFER_VK: vector<u8> =
    x"1d8e4233c3c66ab59c2b3c265a2886837b80219952150d8f2e8bf26fb6dce2aac4c97bbe7457d570a27e0306ebde64269e0a9fd5a9bb0cb070a2824c0b65e710daeb07e8f409c3bd2a195bca7638955741c4590f5d98465d1a6481a2896f6006edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e195767429f909fa9d9627afbb1166c6459625be9b20b0f4e7b5b81afcbfb187624313090e9b38c811b713adaf4da87a519f6c3628b0cbddbbb80567ecfa5faf6280500000000000000c0a9bbb59dd39ee783f7aa64cf28573442b5e08e4372e718046464dcd698501ca6342fbcd957ecf0b9f5995b423194a24f6e0fff2dad01e9dd83cc12db9e0e96e0479f3eff27e39639b45f5bffa23f37126e117423219779346515fd53980787fd4d3b9facc8d3162513617a23beeeb9c4e428dfe2e7f1422d5139b60e1f1e83ecebb66c32f3a4121e3355ea1e8b9ab8014300f6627c2b610563b16fdfd707b0";
const TRANSFER_PROOF: vector<u8> =
    x"48c62568cba82168ed2beb542ebe655de3998b87b6011aa7e5c4c3dbd30c6f27fd6f8c58d846dd7a44eb571d894f02d63e012f4a2ebace0f822d0b5e3678432e465fc57cb724eb4b63e672584b1a684f0bd88350e1513a152cbb7e69b96814a8e519abb893256bf394fd83f296d5c778abf99d25b4e5bbc55125c5b603824f11";
const TRANSFER_INPUTS: vector<u8> =
    x"596ab085862e0366f42e04de276f2b77725fb116487c2b1977efb7f72c999805f5ba88dc63b63544bd3eaad79b0e36436ca59465133cd43c5e0fdd8b37c3b5261ba50e3c7d82093591b1b072c7654c43b8a397ec4a501742199d633486bf851bea3eb9e586671966f301a7e537ce80962d613d68b63f5da10a833d848383322f";

// wrap.circom: enter the confidential balance — public amount $500 bound to a
// commitment with a secret blinding factor. Public signals: [commitment, amount].
const WRAP_VK: vector<u8> =
    x"1d8e4233c3c66ab59c2b3c265a2886837b80219952150d8f2e8bf26fb6dce2aac4c97bbe7457d570a27e0306ebde64269e0a9fd5a9bb0cb070a2824c0b65e710daeb07e8f409c3bd2a195bca7638955741c4590f5d98465d1a6481a2896f6006edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e1998447bbbeddc2ab57f1ec3df3725f5229dcf84b0c4b8a69269616841fd0d101402cf73bc38a6bf326831b3397837d8b50a9c1ca50997439ae23c92d5cdbc1c150300000000000000fa79096d22e37a607c8fb58319dbce0c2e34225163ea33dc71f6bf6e1ff26c99f91a01e098b7476894981a900d771285e8fc6b85106098a216d7204226ec0eb06260e372e904ed13d7793c40283242d8c382466e348c10c6f4992bfdb51674aa";
const WRAP_PROOF: vector<u8> =
    x"5edf256a3af545245d7c6b1a2f94732193c0f3f1f7b3f2216a5e696d77cd1b8799ee019bc3c0bda0233a7f13bdf0069cd01f4c0380722c5ba5a50726ca58081937c5252ae0c85bba58affbec9ddfae0dfa9411d423ff994635b68e68d6b5d7ab23d6ec54ac7a47a5270e67bf8d95a4c2840c31b71c0ac54e47f68811136d82a5";
const WRAP_INPUTS: vector<u8> =
    x"72dfed6bf83459ec874c882737f7a9e312f4e0398ac32b38d4c76d8f4d5c14220065cd1d00000000000000000000000000000000000000000000000000000000";

// unwrap.circom: leave to a public coin — reveal $125 and prove it opens the
// freelancer's commitment. Public signals: [commitment, value].
const UNWRAP_VK: vector<u8> =
    x"1d8e4233c3c66ab59c2b3c265a2886837b80219952150d8f2e8bf26fb6dce2aac4c97bbe7457d570a27e0306ebde64269e0a9fd5a9bb0cb070a2824c0b65e710daeb07e8f409c3bd2a195bca7638955741c4590f5d98465d1a6481a2896f6006edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e19381df03f0666a2752f41a9a55ec66c83273e202b44a2765451bb1827b9ecf10011444f8bd0847dc925827e020a73bb66dda252add7ae227000d56ae78704f8020300000000000000fa79096d22e37a607c8fb58319dbce0c2e34225163ea33dc71f6bf6e1ff26c99f91a01e098b7476894981a900d771285e8fc6b85106098a216d7204226ec0eb06260e372e904ed13d7793c40283242d8c382466e348c10c6f4992bfdb51674aa";
const UNWRAP_PROOF: vector<u8> =
    x"e0be2f8f40f1bdecc6c256098c62996f4fcef0eead822c628877d0c952c97822efcc2275181181e37cc34ee7ef04dd418fd3a9a0bfd61ff82c9cc64c0f3f330d8294a4ba145ed52c254e961293c9ded8e43d1d7827c428072fc4418e9886bf23157d6a9b12a5b98b3d44b2abeb66aa42fc7f715225ada889d5bd7b57d10041ae";
const UNWRAP_INPUTS: vector<u8> =
    x"ea3eb9e586671966f301a7e537ce80962d613d68b63f5da10a833d848383322f4059730700000000000000000000000000000000000000000000000000000000";

#[test]
fun confidential_drip_verifies() {
    assert!(verify(TRANSFER_VK, TRANSFER_INPUTS, TRANSFER_PROOF), 0);
}

#[test]
fun wrap_verifies() {
    assert!(verify(WRAP_VK, WRAP_INPUTS, WRAP_PROOF), 2);
}

#[test]
fun unwrap_verifies() {
    assert!(verify(UNWRAP_VK, UNWRAP_INPUTS, UNWRAP_PROOF), 3);
}

#[test]
fun rejects_forged_commitments() {
    // Flip the last byte of the public commitments — the proof must not verify.
    let mut forged = TRANSFER_INPUTS;
    let last = forged.length() - 1;
    *forged.borrow_mut(last) = 0x00;

    let curve = bn254();
    let pvk = groth16::prepare_verifying_key(&curve, &TRANSFER_VK);
    let inputs = groth16::public_proof_inputs_from_bytes(forged);
    let proof = groth16::proof_points_from_bytes(TRANSFER_PROOF);
    assert!(!groth16::verify_groth16_proof(&curve, &pvk, &inputs, &proof), 1);
}
